
    'address.create',
    'address.get_all',
    'address.get_by_id',
    'address.update',
    'address.delete',

    'agreement_clause.create',
    'agreement_clause.get_all',
    'agreement_clause.get_by_id',
    'agreement_clause.update',
    'agreement_clause.delete',

    'bank_account_details.create',
    'bank_account_details.get_all',
    'bank_account_details.get_by_id',
    'bank_account_details.update',
    'bank_account_details.delete',

    'company.create',
    'company.get_all',
    'company.get_by_id',
    'company.update',
    'company.delete',

    'contract.create',
    'contract.get_all',
    'contract.get_by_id',
    'contract.update',
    'contract.delete',

    'contract_dispute.create',
    'contract_dispute.get_all',
    'contract_dispute.get_by_id',
    'contract_dispute.update',
    'contract_dispute.delete',

    'contract_milestone.create',
    'contract_milestone.get_all',
    'contract_milestone.get_by_id',
    'contract_milestone.update',
    'contract_milestone.delete',

    'notification.create',
    'notification.get_all',
    'notification.get_by_id',
    'notification.update',
    'notification.delete',

    'payment_request.create',
    'payment_request.get_all',
    'payment_request.get_by_id',
    'payment_request.update',
    'payment_request.delete',

    'transaction.create',
    'transaction.get_all',
    'transaction.get_by_id',
    'transaction.update',
    'transaction.delete',

    'user.create',
    'user.get_all',
    'user.get_by_id',
    'user.update',
    'user.delete'
